### ISSUE TITLE
ResizeMode 'overflow' and width property issue

### ISSUE THREAD

**Issue by bravebox** [MonsantoCo/column-resizer#5]
There seems to be an issue when setting the widths property and using the resizeMode overflow. 

When both are set you would expect the width of each cell to math the exact value specified in the widths property. However this is not the case. The width is set on the cell with the correct value initially, but the actual with differs. 

This is how I initialise the library:

````
new colResizable(normal, {
  liveDrag: true,
  gripInnerHtml: "<div class='grip'></div>",
  draggingClass: "dragging",
  resizeMode: 'overflow',
  widths: [275, 350, 500]
});
````

PS when you reload/resize (small resize) the browser it sets the proper values in the DOM.

thanks!

**Comment by jglynn43** [comment]
Hi,
The widths of the cells are a little different due to the padding than the widths of the table headers specified in the options.widths array. Internally, it uses getComputedStyle to reset the column widths on a resize and I have seen wildly different results from different browsers (Chrome and Safari for sure). Also, if you add the flush: true option, it will not use session storage.

Please try the latest version and let me know if this is still an issue. Also, I added your options to the sample in the test.html file so you can test it directly (once it's built).

Thanks!

**Comment by bravebox** [comment]
@jglynn43 Thanks that did work. Also setting the parent container to a large width helped also. Thanks!

**Comment by jglynn43** [comment]
Closing issue
